# Generated by Django 4.2.8 on 2023-12-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='data/images/'
            ),
        ),
    ]
